export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const GET_COUNTRY_ACTIVITY = "GET_COUNTRY_ACTIVITY";
export const FILTER_CONTINENT = "FILTER_CONTINENT";
export const FILTER_ACTIVITY_SEASON = "FILTER_ACTIVITY_SEASON";
export const FILTER_ACTIVITY_DIFFICULTY = "FILTER_ACTIVITY_DIFFICULTY";
export const ORDER_ALPH = "ORDER_ALPH";
export const ORDER_POPULATION = "ORDER_POPULATION";
export const RESET = "RESET";
export const RESET_CONTINET = "RESET_CONTINET";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const POST_ACTIVITY = "POST_ACTIVITY";
export const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES"
export const CLEAR_STATE = "CLEAR_STATE" ;
export const ERROR = "ERROR" 

